name: Refresh Charts and Deploy to GitHub Pages

on:
  schedule:
    # - cron: '*/5 * * * *' # Every 5 minutes
    - cron: '0 10 * * *' # Every day at 10 AM
  workflow_dispatch:  # Allows manual triggering

jobs:
  refresh-charts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        ref: 'main'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache Python environment
      id: cache-python-env
      uses: actions/cache@v3
      with:
        path: .venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt', '**/.python-version') }}
        restore-keys: |
          ${{ runner.os }}-venv-

    - name: Install Python environment
      if: steps.cache-python-env.outputs.cache-hit != 'true'
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: Run project code to generate charts
      run: |
        source .venv/bin/activate
        doit

    - name: Setup Git
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"

    - name: Create/Update gh-pages branch
      run: |
        # Create a new branch from current main or update existing one
        git checkout -B gh-pages
        
        # Force add the docs directory (override gitignore)
        git add -f docs/
        
        # Commit changes
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update charts and documentation [skip ci]"
        fi
        
        # Force push to gh-pages
        git push -f origin gh-pages